app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
Route::get('home','HomeController@index');
Route::get('ejemplo1','HomeController@index');
Route::get('/','HomeController@index');

Route::get('/', function () {
    return view('home.index');
});

Route::get('ejemplo', function () {
    return view('home.ejemplo1');
});

Route::get('ejemplo', function () {
    return view('home.ejemplo1');
});

Route::get('/', function () {
    return view('home.welcome');
});
Route::resource('home','HomeController');
// Para Desabilitar la gestion de creacion de usuarios.
Route::get('register', 'Auth\AuthController@showRegistrationForm');
Route::post('register', 'Auth\AuthController@register');

*/

Route::get('/','HomeController@index');

Route::get('home','HomeController@index');

Route::get('atentados','AtentadosController@index');

Route::get('validarcliente','ClientesJsonController@validarcliente');

Route::resource('clientes','ClientesController');

Route::resource('usuarios','UsuariosController');

Route::auth();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Odoo Validate Me - Autenticated User</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    
    {!! Html::style('css/bootstrap.css') !!}
    {!! Html::style('css/site.css') !!}
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
            padding-top: 0px !important; 
        }

        .fa-btn {
            margin-right: 6px;
        }

        .popover {
            max-width: 900px !important;
            word-wrap: break-word;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Odoo Validate Me
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                @if (Auth::guest())
                    <span></span>
                @else
                    <ul class="nav navbar-nav"> 
                        <li><a href="{{ route('clientes.index') }}">Clientes</a></li> 
                        <li><a href="{{ route('clientes.create') }}">Nuevo Cliente</a></li> 
                        <li><a href="{{ route('usuarios.index') }}">Usuarios</a></li> 
                        <li><a href="{{ url('/usuarios/create') }}">Nuevo Usuario</a></li> 
                        <li><a href="{{ url('/atentados') }}">Atentados</a></li> 
                    </ul>
                @endif
                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    {!! Html::script('js/jquery-2.2.3.min.js') !!}
    {!! Html::script('js/bootstrap.min.js') !!}
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
    <script type="text/javascript"> 
        $(document).ready(function() {
            $('.navbar-collapse a[href="'+location.href+'"]').parents('li').addClass('active');
            $('[data-toggle="popover"]').popover();
        });
    </script>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	{!! Html::style('css/bootstrap.css') !!}
	{!! Html::style('css/site.css') !!}
	<!--<link type="text/css" rel="stylesheet" href="css/bootstrap.css">-->
	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header" style="margin-right: 15px;">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{{ route('home.index') }}">Laravel!</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav"> 
          	<li class="active"><a href="{{ route('artes.index') }}">Artes</a></li> 
            <li><a href="{{ route('artes.create') }}">Crear</a></li> 
          	<li><a href="#">Link</a></li> 
          	<li><a href="#">Link</a></li> 
          </ul>
          <form class="navbar-form navbar-right" role="form" method="POST" action="{{ url('/login') }}">
            <div class="form-group">
              <input type="email" class="form-control" name="email" placeholder="Email" value="{{ old('email') }}">
            </div>
            <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

	@yield('content')

	<!-- Scripts -->
	{!! Html::script('js/jquery-2.2.3.min.js') !!}
	{!! Html::script('js/bootstrap.min.js') !!}
	<!-- 
		<script src="js/jquery-2.2.3.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
	-->

</body>
</html>